<?php

namespace WSMD;

class WSMD_Dummy_Data{
    public static function get_members(){

        // Québec dummy data
        return [
            '1' => [
                'wsmd_visibility' => 'default',
                'wsmd_geocode' => '46.8138783, -71.2079809',
                'wsmd_occupation' => 'Graphic Designer',
                'wsmd_company' => 'Creative Designs',
                'wsmd_address' => '123 Art Lane',
                'wsmd_city' => 'Québec City',
                'wsmd_province_state' => 'Québec',
                'wsmd_postal_zip_code' => 'G1R 4P1',
                'wsmd_country' => 'Canada',
                'wsmd_website' => 'http://creativedesigns.com',
                'wsmd_phone' => '418-555-0101',
                'wsmd_email' => 'info@creativedesigns.com'
            ],
            '2' => [
                'wsmd_visibility' => 'default',
                'wsmd_geocode' => '45.5016889, -73.567256',
                'wsmd_occupation' => 'Tech Entrepreneur',
                'wsmd_company' => 'Innovatech',
                'wsmd_address' => '400 Tech Avenue',
                'wsmd_city' => 'Montréal',
                'wsmd_province_state' => 'Québec',
                'wsmd_postal_zip_code' => 'H2Z 1G1',
                'wsmd_country' => 'Canada',
                'wsmd_website' => 'http://innovatech.com',
                'wsmd_phone' => '514-555-0192',
                'wsmd_email' => 'contact@innovatech.com'
            ],
            '3' => [
                'wsmd_visibility' => 'default',
                'wsmd_geocode' => '45.4009928, -71.8824288',
                'wsmd_occupation' => 'Museum Curator',
                'wsmd_company' => 'History Québec',
                'wsmd_address' => '789 Cultural Rd',
                'wsmd_city' => 'Sherbrooke',
                'wsmd_province_state' => 'Québec',
                'wsmd_postal_zip_code' => 'J1H 1K1',
                'wsmd_country' => 'Canada',
                'wsmd_website' => 'http://historyquebec.com',
                'wsmd_phone' => '819-555-0113',
                'wsmd_email' => 'curator@historyquebec.com'
            ],
            '4' => [
                'wsmd_visibility' => 'default',
                'wsmd_geocode' => '48.4200335, -71.0524504',
                'wsmd_occupation' => 'Brewmaster',
                'wsmd_company' => 'La Saguenéenne',
                'wsmd_address' => '255 Brewery Blvd',
                'wsmd_city' => 'Saguenay',
                'wsmd_province_state' => 'Québec',
                'wsmd_postal_zip_code' => 'G7H 7P2',
                'wsmd_country' => 'Canada',
                'wsmd_website' => 'http://lasaguenéenne.com',
                'wsmd_phone' => '418-555-0124',
                'wsmd_email' => 'brew@lasaguenéenne.com'
            ],
            '5' => [
                'wsmd_visibility' => 'default',
                'wsmd_geocode' => '45.378789, -72.733006',
                'wsmd_occupation' => 'Hotel Manager',
                'wsmd_company' => 'Château Étoile',
                'wsmd_address' => '25 Starlight Drive',
                'wsmd_city' => 'Magog',
                'wsmd_province_state' => 'Québec',
                'wsmd_postal_zip_code' => 'J1X 3W9',
                'wsmd_country' => 'Canada',
                'wsmd_website' => 'http://chateauetoile.com',
                'wsmd_phone' => '819-555-0165',
                'wsmd_email' => 'manager@chateauetoile.com'
            ],
            '6' => [
                'wsmd_visibility' => 'default',
                'wsmd_geocode' => '46.3421266, -72.5477492',
                'wsmd_occupation' => 'Chef',
                'wsmd_company' => 'La Bonne Fourchette',
                'wsmd_address' => '500 Gourmet St',
                'wsmd_city' => 'Trois-Rivières',
                'wsmd_province_state' => 'Québec',
                'wsmd_postal_zip_code' => 'G9A 5C9',
                'wsmd_country' => 'Canada',
                'wsmd_website' => 'http://labonnefourchette.com',
                'wsmd_phone' => '819-555-0176',
                'wsmd_email' => 'chef@labonnefourchette.com'
            ]
        ];
        
        // International dummy data
        // return [
        //     '1' => [
        //         'wsmd_visibility' => 'default',
        //         'wsmd_geocode' => '47.21025, -123.10040',
        //         'wsmd_occupation' => 'Software Developer',
        //         'wsmd_company' => 'Tech Solutions',
        //         'wsmd_address' => '120 Tech Park',
        //         'wsmd_city' => 'Seattle',
        //         'wsmd_province_state' => 'Washington',
        //         'wsmd_postal_zip_code' => '98101',
        //         'wsmd_country' => 'USA',
        //         'wsmd_website' => 'http://techsolutions.com',
        //         'wsmd_phone' => '206-555-0144',
        //         'wsmd_email' => 'contact@techsolutions.com'
        //     ],
        //     '2' => [
        //         'wsmd_visibility' => 'default',
        //         'wsmd_geocode' => '46.8138783, -71.2079809',
        //         'wsmd_occupation' => 'Graphic Designer',
        //         'wsmd_company' => 'Creative Minds',
        //         'wsmd_address' => '33 Art Street',
        //         'wsmd_city' => 'Quebec City',
        //         'wsmd_province_state' => 'Quebec',
        //         'wsmd_postal_zip_code' => 'G1R 4S9',
        //         'wsmd_country' => 'Canada',
        //         'wsmd_website' => 'http://creativeminds.com',
        //         'wsmd_phone' => '418-555-0132',
        //         'wsmd_email' => 'info@creativeminds.com'
        //     ],
        //     '3' => [
        //         'wsmd_visibility' => 'default',
        //         'wsmd_geocode' => '48.856614, 2.3522219',
        //         'wsmd_occupation' => 'Architect',
        //         'wsmd_company' => 'Build Right',
        //         'wsmd_address' => '88 Builder Blvd',
        //         'wsmd_city' => 'Paris',
        //         'wsmd_province_state' => 'Ile-de-France',
        //         'wsmd_postal_zip_code' => '75004',
        //         'wsmd_country' => 'France',
        //         'wsmd_website' => 'http://buildright.com',
        //         'wsmd_phone' => '+33 1 70 23 01 23',
        //         'wsmd_email' => 'contact@buildright.com'
        //     ],
        //     '4' => [
        //         'wsmd_visibility' => 'default',
        //         'wsmd_geocode' => '51.5073509, -0.1277583',
        //         'wsmd_occupation' => 'Marketing Specialist',
        //         'wsmd_company' => 'Market Pro',
        //         'wsmd_address' => '55 Market Street',
        //         'wsmd_city' => 'London',
        //         'wsmd_province_state' => 'England',
        //         'wsmd_postal_zip_code' => 'SW1A 1AA',
        //         'wsmd_country' => 'UK',
        //         'wsmd_website' => 'http://marketpro.com',
        //         'wsmd_phone' => '+44 20 5555 0123',
        //         'wsmd_email' => 'info@marketpro.com',
        //     ],
        //     '5' => [
        //         'wsmd_visibility' => 'default',
        //         'wsmd_geocode' => '40.7127753, -74.0059728',
        //         'wsmd_occupation' => 'Photographer',
        //         'wsmd_company' => 'Photo World',
        //         'wsmd_address' => '77 Photo Avenue',
        //         'wsmd_city' => 'New York',
        //         'wsmd_province_state' => 'New York',
        //         'wsmd_postal_zip_code' => '10007',
        //         'wsmd_country' => 'USA',
        //         'wsmd_website' => 'http://photoworld.com',
        //         'wsmd_phone' => '212-555-0134',
        //         'wsmd_email' => 'info@photoworld.com',
        //     ],
        //     '6' => [
        //         'wsmd_visibility' => 'default',
        //         'wsmd_geocode' => '35.6894875, 139.6917064',
        //         'wsmd_occupation' => 'Chef',
        //         'wsmd_company' => 'Taste Buds',
        //         'wsmd_address' => '22 Chef Street',
        //         'wsmd_city' => 'Tokyo',
        //         'wsmd_province_state' => 'Tokyo',
        //         'wsmd_postal_zip_code' => '100-0005',
        //         'wsmd_country' => 'Japan',
        //         'wsmd_website' => 'http://tastebuds.com',
        //         'wsmd_phone' => '+81 3-5555-0122',
        //         'wsmd_email' => 'info@tastebuds.com',
        //     ],
        //     '7' => [
        //         'wsmd_visibility' => 'default',
        //         'wsmd_geocode' => '52.5200066, 13.404954',
        //         'wsmd_occupation' => 'Web Developer',
        //         'wsmd_company' => 'Web Innovations',
        //         'wsmd_address' => '200 Tech Park',
        //         'wsmd_city' => 'Berlin',
        //         'wsmd_province_state' => 'Berlin',
        //         'wsmd_postal_zip_code' => '10115',
        //         'wsmd_country' => 'Germany',
        //         'wsmd_website' => 'http://webinnovations.com',
        //         'wsmd_phone' => '+49 30 123456',
        //         'wsmd_email' => 'contact@webinnovations.com'
        //     ],
        //     '8' => [
        //         'wsmd_visibility' => 'default',
        //         'wsmd_geocode' => '-33.8688197, 151.2092955',
        //         'wsmd_occupation' => 'Interior Designer',
        //         'wsmd_company' => 'Designs Studio',
        //         'wsmd_address' => '88 Design Street',
        //         'wsmd_city' => 'Sydney',
        //         'wsmd_province_state' => 'New South Wales',
        //         'wsmd_postal_zip_code' => '2000',
        //         'wsmd_country' => 'Australia',
        //         'wsmd_website' => 'http://designsstudio.com',
        //         'wsmd_phone' => '+61 2 1234 5678',
        //         'wsmd_email' => 'hello@designsstudio.com'
        //     ],
        //     '9' => [
        //         'wsmd_visibility' => 'default',
        //         'wsmd_geocode' => '34.0522342, -118.2436849',
        //         'wsmd_occupation' => 'Real Estate Agent',
        //         'wsmd_company' => 'Estate Plus',
        //         'wsmd_address' => '101 Realty Drive',
        //         'wsmd_city' => 'Los Angeles',
        //         'wsmd_province_state' => 'California',
        //         'wsmd_postal_zip_code' => '90015',
        //         'wsmd_country' => 'USA',
        //         'wsmd_website' => 'http://estateplus.com',
        //         'wsmd_phone' => '213-555-0189',
        //         'wsmd_email' => 'sales@estateplus.com'
        //     ],
        //     '10' => [
        //         'wsmd_visibility' => 'default',
        //         'wsmd_geocode' => '55.755826, 37.6172999',
        //         'wsmd_occupation' => 'Event Planner',
        //         'wsmd_company' => 'Events Deluxe',
        //         'wsmd_address' => '32 Festive Road',
        //         'wsmd_city' => 'Moscow',
        //         'wsmd_province_state' => 'Moscow',
        //         'wsmd_postal_zip_code' => '125009',
        //         'wsmd_country' => 'Russia',
        //         'wsmd_website' => 'http://eventsdeluxe.com',
        //         'wsmd_phone' => '+7 495 123 4567',
        //         'wsmd_email' => 'info@eventsdeluxe.com'
        //     ],
        //     '11' => [
        //         'wsmd_visibility' => 'default',
        //         'wsmd_geocode' => '39.9041999, 116.4073963',
        //         'wsmd_occupation' => 'IT Consultant',
        //         'wsmd_company' => 'Tech Advisors',
        //         'wsmd_address' => '48 High Tech Road',
        //         'wsmd_city' => 'Beijing',
        //         'wsmd_province_state' => 'Beijing',
        //         'wsmd_postal_zip_code' => '100000',
        //         'wsmd_country' => 'China',
        //         'wsmd_website' => 'http://techadvisors.com',
        //         'wsmd_phone' => '+86 10 1234 5678',
        //         'wsmd_email' => 'contact@techadvisors.com'
        //     ],
        //     '12' => [
        //         'wsmd_visibility' => 'default',
        //         'wsmd_geocode' => '19.0759837, 72.8776559',
        //         'wsmd_occupation' => 'Fashion Designer',
        //         'wsmd_company' => 'Fashion Forward',
        //         'wsmd_address' => '25 Trendy Lane',
        //         'wsmd_city' => 'Mumbai',
        //         'wsmd_province_state' => 'Maharashtra',
        //         'wsmd_postal_zip_code' => '400013',
        //         'wsmd_country' => 'India',
        //         'wsmd_website' => 'http://fashionforward.com',
        //         'wsmd_phone' => '+91 22 1234 5678',
        //         'wsmd_email' => 'designs@fashionforward.com'
        //     ],
        //     '13' => [
        //         'wsmd_visibility' => 'default',
        //         'wsmd_geocode' => '41.9027835, 12.4963655',
        //         'wsmd_occupation' => 'Art Dealer',
        //         'wsmd_company' => 'Classic Arts',
        //         'wsmd_address' => '77 Gallery Road',
        //         'wsmd_city' => 'Rome',
        //         'wsmd_province_state' => 'Lazio',
        //         'wsmd_postal_zip_code' => '00184',
        //         'wsmd_country' => 'Italy',
        //         'wsmd_website' => 'http://classicarts.com',
        //         'wsmd_phone' => '+39 06 1234 5678',
        //         'wsmd_email' => 'info@classicarts.com'
        //     ],
        //     '14' => [
        //         'wsmd_visibility' => 'default',
        //         'wsmd_geocode' => '-34.6036844, -58.3815591',
        //         'wsmd_occupation' => 'Dance Instructor',
        //         'wsmd_company' => 'Step Up Studio',
        //         'wsmd_address' => '59 Dance Blvd',
        //         'wsmd_city' => 'Buenos Aires',
        //         'wsmd_province_state' => 'Buenos Aires',
        //         'wsmd_postal_zip_code' => 'C1053',
        //         'wsmd_country' => 'Argentina',
        //         'wsmd_website' => 'http://stepupstudio.com',
        //         'wsmd_phone' => '+54 11 1234 5678',
        //         'wsmd_email' => 'dance@stepupstudio.com'
        //     ],
        //     '15' => [
        //         'wsmd_visibility' => 'default',
        //         'wsmd_geocode' => '35.6895, 139.6917',
        //         'wsmd_occupation' => 'Game Developer',
        //         'wsmd_company' => 'Pixel Games',
        //         'wsmd_address' => '88 Gaming Arcade',
        //         'wsmd_city' => 'Tokyo',
        //         'wsmd_province_state' => 'Tokyo',
        //         'wsmd_postal_zip_code' => '160-0022',
        //         'wsmd_country' => 'Japan',
        //         'wsmd_website' => 'http://pixelgames.com',
        //         'wsmd_phone' => '+81 3-1234-5678',
        //         'wsmd_email' => 'support@pixelgames.com'
        //     ],
        //     '16' => [
        //         'wsmd_visibility' => 'default',
        //         'wsmd_geocode' => '51.5074, -0.1278',
        //         'wsmd_occupation' => 'Professional Speaker',
        //         'wsmd_company' => 'SpeakWell',
        //         'wsmd_address' => '100 Speaker\'s Corner',
        //         'wsmd_city' => 'London',
        //         'wsmd_province_state' => 'England',
        //         'wsmd_postal_zip_code' => 'SW1A 2BJ',
        //         'wsmd_country' => 'UK',
        //         'wsmd_website' => 'http://speakwell.com',
        //         'wsmd_phone' => '+44 20 7946 0987',
        //         'wsmd_email' => 'contact@speakwell.com'
        //     ],
        //     '17' => [
        //         'wsmd_visibility' => 'default',
        //         'wsmd_geocode' => '40.7128, -74.0060',
        //         'wsmd_occupation' => 'Financial Analyst',
        //         'wsmd_company' => 'WealthGenius',
        //         'wsmd_address' => '200 Financial District',
        //         'wsmd_city' => 'New York',
        //         'wsmd_province_state' => 'New York',
        //         'wsmd_postal_zip_code' => '10005',
        //         'wsmd_country' => 'USA',
        //         'wsmd_website' => 'http://wealthgenius.com',
        //         'wsmd_phone' => '+1 212-555-1234',
        //         'wsmd_email' => 'info@wealthgenius.com'
        //     ],
        //     '18' => [
        //         'wsmd_visibility' => 'default',
        //         'wsmd_geocode' => '48.8566, 2.3522',
        //         'wsmd_occupation' => 'Fashion Blogger',
        //         'wsmd_company' => 'Fashion Finds',
        //         'wsmd_address' => '75 Chic Street',
        //         'wsmd_city' => 'Paris',
        //         'wsmd_province_state' => 'Île-de-France',
        //         'wsmd_postal_zip_code' => '75004',
        //         'wsmd_country' => 'France',
        //         'wsmd_website' => 'http://fashionfinds.com',
        //         'wsmd_phone' => '+33 1 2345 6789',
        //         'wsmd_email' => 'info@fashionfinds.com',
        //     ],      
        // ];
    }
}